### ISSUE TITLE
Se över rubriknumreringen i teorin, nu är det ganska blandat med numrering vs icke-numrering på underrubrikerna

### ISSUE THREAD

**Issue by johannity** [ProffOak/KandidatRapport2#72]

**Comment by jakobsanne** [comment]
Det är bara numrerat till nivå x.x och det gäller hela rapporten, tycker inte det finns anledning att ändra detta. Vissa rubriknamn är dock lite otydliga fortfarande

**Comment by johannity** [comment]
De rubriker som har med tester att göra har nummer framför sig och är väldigt korta, borde inte de ligga under en gemensam numrerad rubrik likt de övriga "huvudämnena". Min åsikt men om ni andra inte håller med behöver vi inte ändra :)

**Comment by jakobsanne** [comment]
Aha men jag tror det är för att det ska följa teorin i upplägget för testerna, de är inte numrerade rubriker alls utan bara siffror som råkar stå där. Håller dock med, de kan strykas.
